Draft: Make makefile possible to use in common
clear-code/firefox-support-common pull request #38
Opened 2024-04-12 09:01 UTC by yashirot

Prior to moving all the skus,
* Move the existing Makefile to directly under "sku" directory to use in common.
* Modify Makefile which the individual sku has to refer to the common.

For Makefile in just under "sku":
It might be more concise way to write the code, but unfortunately I don't know much about that.

For Makefile under windows-11-23H2:
Almost copy&pasted from that in other repos.

2024-04-16 08:02 UTC, kenhys requested changes

2024-04-16 08:02 UTC, kenhys commented on verify/terraform/skus/windows-11-23H2/Makefile
> +include ../Makefile
verify/terraform ディレクトリにいるときにうっかりmakeで誤爆しないですむように
ファイル名をMakefileじゃないものにしませんか。(rule.mkとかそんな感じでなにか適切な名前を)

2024-04-16 08:14 UTC, yashirot commented on verify/terraform/skus/windows-11-23H2/Makefile
> +include ../Makefile
skus直下のスクリプトは`use-in-common.mk`にリネームしました。

2024-04-16 08:37 UTC, piroor approved these changes
このリポジトリー内の構成としては、これでいいように思います。
あとは、 https://github.com/ThinBridge/ThinBridge/tree/master/doc/verify のように、既存プロジェクト内に持ち込む場合のおすすめの使い方を文書化できるといいんですが、どう使うのがいいですかねぇ。

2024-04-17 01:57 UTC, yashirot commented
> あとは、 https://github.com/ThinBridge/ThinBridge/tree/master/doc/verify のように、既存プロジェクト内に持ち込む場合のおすすめの使い方を文書化できるといいんですが、どう使うのがいいですかねぇ。

I will think it over.

2024-04-17 03:09 UTC, yashirot commented
Let me move it forward even though this PR still has a pending reviewer.

2024-04-17 03:09 UTC, merged