Refactor one more SKU to use modules
clear-code/firefox-support-common pull request #40
Opened 2024-04-18 07:25 UTC by yashirot

Partly resolves Issue #34 

As the 2nd PR after PR #35, I will move win10-21h2-ent, which is the latest among existing win10 skus, then fixed to work as before with use of modules.

2024-04-19 05:52 UTC, kenhys requested changes

2024-04-19 05:52 UTC, kenhys commented on verify/terraform/skus/.gitignore
> +/*/rdp/*.rdp
.gitignoreあちこちでメンテナンスするの不毛なので集約しませんか。

```
find . -name .gitignore
./.gitignore
./verify/terraform/skus/.gitignore
./verify/terraform/skus/windows-11-23H2/ansible/.gitignore
./verify/terraform/skus/windows-10-21H2/ansible/.gitignore
./verify/terraform/windows-server-2022/ansible/.gitignore
./verify/terraform/windows-server-2022/.gitignore
./verify/terraform/windows-10-1909/ansible/.gitignore
./verify/terraform/windows-10-1909/.gitignore
./verify/terraform/windows-11-22H2/ansible/.gitignore
./verify/terraform/windows-11-22H2/.gitignore
./verify/terraform/windows-11-21H2/ansible/.gitignore
./verify/terraform/windows-11-21H2/.gitignore
./verify/terraform/windows-10-zh-cn-21H2/ansible/.gitignore
./verify/terraform/windows-10-zh-cn-21H2/.gitignore
./verify/terraform/windows-10-2016-LTSB/ansible/.gitignore
./verify/terraform/windows-10-2016-LTSB/.gitignore
./verify/terraform/windows-10-1903/ansible/.gitignore
./verify/terraform/windows-10-1903/.gitignore
```

ひとまずこのPRでは./verify/terraform/skus/windows-11-23H2/ansible/.gitignoreを消してトップレベルの.gitignoreに集約する

2024-04-19 05:54 UTC, yashirot commented on verify/terraform/skus/.gitignore
> +/*/rdp/*.rdp
> ひとまずこのPRでは./verify/terraform/skus/windows-11-23H2/ansible/.gitignoreを消してトップレベルの.gitignoreに集約する

そうですね。その方向で修正します。

2024-04-19 07:44 UTC, yashirot commented on verify/terraform/skus/.gitignore
> +/*/rdp/*.rdp
現状の各skuの/ansible/.gitignore 内容は
```
hosts
playbook.yml
```
です。
`/*/ansible/hosts`、`/*/ansible/playbook.yml`のように限定しないで、この内容のまま統合します。

2024-04-22 01:22 UTC, kenhys approved these changes
LGTM.

2024-04-22 01:23 UTC, merged